### ISSUE TITLE
The example in the Readme could better explained better at the end.

### ISSUE THREAD

**Issue by jmckinnell** [Jam3/tween-function#1]
If you used a for loop or a RAF to iterate through time and log the result in the last part of the example in the Readme it would better explain what the values of the tween function were and what the expected result was.

Something like this to show that this is to be used multiple times and iterate through a time value that's in seconds.

```
// from 0 to 10 seconds
for(time=0;time<=10;time++){
 console.log( tween( time, start, end ) ); // value with ease applied
}
```

**Comment by mikkoh** [comment]
Sure sounds good. Feel free to make a PR. ;)
